main:
  - name: Home
    url: '/#about'
    weight: 10
  - name: News
    url: '/#news'
    weight: 15
  - name: Publications
    identifier: publications
    url: '/select-pubs/'
    weight: 20
  - name: 'Highlights '
    parent: publications
    url: '/select-pubs/'
    weight: 10
  - name: 'All '
    parent: publications
    url: '/publications/'
    weight: 20
  - name: Presentations
    identifier: talks
    url: '/select-talks/'
    weight: 30
  - name: Highlights
    parent: talks
    url: '/select-talks/'
    weight: 10
  - name: All
    parent: talks
    url: '/talks/'
    weight: 20
  - name: Projects
    url: '/projects/'
    weight: 40
  - name: Awards
    url: '/awards/'
    weight: 50
  - name: CV
    url: '/uploads/CV.pdf'
    weight: 100
  - name: Blog
    url: 'https://rkansal47.github.io/'
    weight: 110
  - name: Notes and Tutorials
    identifier: Notes
    url: 'https://rkansal47.github.io/#notes'
    weight: 120
  - name: 'Standard Model'
    parent: Notes
    url: 'https://rkansal47.github.io/standard-model/'
    weight: 10
  - name: 'Stats for HEP'
    parent: Notes
    url: 'https://rkansal47.github.io/stats-for-hep/'
    weight: 20
  - name: 'ML for HEP'
    parent: Notes
    url: 'https://fnallpc.github.io/machine-learning-hats/'
    weight: 30
  - name: 'LHC and CMS'
    parent: Notes
    url: 'https://rkansal47.github.io/dissertation/ExperimentalBackground.html'
    weight: 40
